routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::middleware('auth')->group(function () {
Route::middleware('admin')->prefix('admin')->group(function () {
  Route::get('index', function(){
    return view('admin.index');
  });

  Route::resource('Order', 'OrderController');
  Route::resource('User', 'UserController');
  Route::resource('Driver', 'DriverController');
  Route::resource('Client', 'ClientController');
  Route::resource('Business', 'BusinessController');
 Route::resource('Collector', 'CollectorController');




});
});

resources/views/admin/index.blade.php
@extends('admin.nlayout')
@section('content')
<div class="row">
    <div class="col-md-6 col-xl-3">
        <div class="card-box tilebox-one">
            <i class="icon-layers float-right m-0 h2 text-muted"></i>
            <h6 class="text-muted text-uppercase mt-0">الطلبات</h6>
            <h3 class="my-3" data-plugin="counterup">{{\App\Order::orderBy('id','desc')->count()}}</h3>
            <span class="badge badge-success mr-1"> +11% </span> <span class="text-muted">الزيادة الحالية</span>
        </div>
    </div>

    <div class="col-md-6 col-xl-3">
        <div class="card-box tilebox-one">
            <i class="icon-paypal float-right m-0 h2 text-muted"></i>
            <h6 class="text-muted text-uppercase mt-0">الأرباح</h6>
            <h3 class="my-3">$<span data-plugin="counterup">{{\DB::table('orders')->where('status',5)->sum('total')}}</span></h3>
            <span class="badge badge-danger mr-1"> +29% </span> <span class="text-muted">الزيادة الحالية</span>
        </div>
    </div>

    <div class="col-md-6 col-xl-3">
        <div class="card-box tilebox-one">
            <i class="icon-chart float-right m-0 h2 text-muted"></i>
            <h6 class="text-muted text-uppercase mt-0">السعر المتوسط للطلبات</h6>
            <h3 class="my-3">$<span data-plugin="counterup">{{\DB::table('orders')->avg('total')}}</span></h3>
              <span class="badge badge-danger mr-1"> +29% </span> <span class="text-muted">الزيادة الحالية</span>
        </div>
    </div>

    <div class="col-md-6 col-xl-3">
        <div class="card-box tilebox-one">
            <i class="icon-rocket float-right m-0 h2 text-muted"></i>
            <h6 class="text-muted text-uppercase mt-0">عدد الطلبات الناجحة</h6>
            <h3 class="my-3" data-plugin="counterup">{{\DB::table('orders')->where('status',5)->count()}}</h3>
            <span class="badge badge-warning mr-1"> +89% </span> <span class="text-muted">الزيادة الحالية</span>
        </div>
    </div>
</div>
<!-- end row -->

<div class="row">
    <div class="col-xl-7">
        <div class="row">
            <div class="col-md-12">
                <div class="card-box">
                    <h4 class="header-title mb-3">آخر المستخدمين</h4>

                    <div class="inbox-widget slimscroll" style="max-height: 324px;">
                      @php
                      $ds =   \App\User::orderBy('id','desc')->take(20)->get();
                      @endphp
                        @foreach ($ds as $d)
                        <a href="{{route('User.edit',$d->id)}}">
                            <div class="inbox-item">
                                <div class="inbox-item-img"><img src="{{asset('nass/images/users/avatar-1.jpg')}}" class="rounded-circle" alt=""></div>
                                <p class="inbox-item-author">{{$d->name}}</p>
                                <p class="inbox-item-text">{{$d->phone}}</p>
                                <p class="inbox-item-date">{{$d->created_at}}</p>
                            </div>
                        </a>
                      @endforeach


                    </div>

                </div>
            </div>



        </div>
    </div><!-- end col-->

    {{-- <div class="col-xl-5">
        <div class="card-box">

            <h4 class="header-title mb-3">آخر الدفعات المالية</h4>

            <div class="table-responsive">
                <table class="table table-bordered table-nowrap mb-0">
                    <thead>
                        <tr>
                            <th>دفعة من</th>
                            <th>الطلب</th>
                            <th>المبلغ</th>
                            <th>الحالة</th>
                        </tr>
                    </thead>
                    <tbody>
                      @php
                        $orders = \App\Order::where('status',4)->orderBy('id','desc')->with('borrower')->take(6)->get();
                      @endphp
                      @foreach ($orders as $order)
                        <tr>
                            <th class="text-muted">{{$order->borrower->name}}</th>
                            <td>{{$order->id}}</td>
                            <td>{{$order->total}}</td>
                            <td><span class="badge badge-success">تم الدفع</span></td>
                        </tr>
                      @endforeach


                    </tbody>
                </table>
            </div>
        </div>
    </div><!-- end col-->

    <div class="col-xl-12">
        <div class="card-box">

            <h4 class="header-title mb-3">سيارات بانتظار رد الادارة</h4>

            <div class="table-responsive">
                <table class="table table-bordered table-nowrap mb-0">
                    <thead>
                        <tr>
                           <th>اسم السيارة</th>
                            <th>صاحب السيارة</th>
                             <th>الصورة</th>
                              <th>مزيد من التفاصيل</th>
                              <th>تغيير الحالة</th>
                        </tr>
                    </thead>
                    <tbody>
                      @php
                        $cars = \App\Car::where('status',1)->orderBy('id','desc')->with('user')->take(10)->get();
                      @endphp
                      @foreach ($cars as $car)
                        <tr>
                            <th class="text-muted">{{$car->title}}</th>
                            <td>{{$car->user->name}}</td>
                            <td> <img src="{{asset($car->full_photo)}}" width="100px"></td>
                            <td>  <a href="{{ route('Car.edit',$car->id) }}" data-toggle="tooltip" data-original-title="عرض"> <i class="fa fa-eye" style="padding-right:10px"></i> </a></td>

                            <td>
                                <a href="{{ url('admin/acceptCar?id='.$car->id) }}" class="btn btn-success">موافقة </a>
                                 <a href="{{ url('admin/rejectCar?id='.$car->id) }}" class="btn btn-danger">رفض </a>
                                </td>
                        </tr>
                      @endforeach


                    </tbody>
                </table>
            </div>
        </div>
    </div><!-- end col--> --}}

</div>
@endsection

resources/views/admin/layout.blade.php
<!DOCTYPE html>
<html lang="ar">
<head>
    <base href="{{ URL::asset('/') }}"/>
    <title>
      Syartech
        |
        @yield('title')
    </title>
    <!-- META SECTION -->
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <link rel="shortcut icon" href="favicon.ico" type="image/x-icon">
    <link rel="icon" href="favicon.ico" type="image/x-icon">
    <!-- END META SECTION -->
    <!-- CSS INCLUDE -->
    <link rel="stylesheet" href="{{asset('admin/css/styles.css')}}">
    <link rel="stylesheet" href="{{asset('admin/css/bootstrap-rtl.min.css')}}">

    <!-- EOF CSS INCLUDE -->
    @yield('header')

</head>
<body>


<!-- APP WRAPPER -->
<div class="app app-rtl">

    <!-- START APP CONTAINER -->
    <div class="app-container">

        <!-- START SIDEBAR -->
        <div class="app-sidebar app-navigation app-navigation-style-default dir-right" data-type="close-other">
            <a href="/admin"></a>
            <h3 style="color:white; text-align: center;line-height: 80px">Education system</h3>
            @include('admin.nav')
        </div>
        <!-- END SIDEBAR -->

        <!-- START APP CONTENT -->
        <div class="app-content app-sidebar-right">
            <!-- START APP HEADER -->
            <div class="app-header">
                <ul class="app-header-buttons">
                    <li>
                        <div class="contact contact-rounded contact-bordered contact-lg contact-ps-controls">
                            <img src="{{asset('assets/images/prlogoAsset 1.png')}}" alt="">
                            <div class="contact-container">
                                <a href="#">kk</a>
                                <span>مدير للموقع</span>
                            </div>
                            <div class="contact-controls">
                                <div class="dropdown">
                                    <button type="button" class="btn btn-default btn-icon" data-toggle="dropdown"><span class="icon-cog"></span></button>
                                    <ul class="dropdown-menu dropdown-left">
                                        <li>  <a href="{{ route('logout') }}"
                                                 onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                                <span class="icon-exit-right"></span> تسجيل الخروج
                                            </a>
                                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                                {{ csrf_field() }}
                                            </form>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </li>
                </ul>

                <ul class="app-header-buttons pull-right">
                    <li class="visible-mobile"><a href="#" class="btn btn-link btn-icon" data-sidebar-toggle=".app-sidebar.dir-right"><span class="icon-menu"></span></a></li>
                    <li class="hidden-mobile"><a href="#" class="btn btn-link btn-icon" data-sidebar-minimize=".app-sidebar.dir-right"><span class="icon-list"></span></a></li>
                </ul>
            </div>
            <!-- END APP HEADER  -->

            @yield('content')

        </div>
        <!-- END APP CONTENT -->

    </div>
    <!-- END APP CONTAINER -->

    <!-- START APP FOOTER
    <div class="app-footer app-footer-default" id="footer">

        <div class="alert alert-primary alert-dismissible alert-inside text-center">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span class="icon-cross"></span></button>

            نقوم باستخدام الكوكيز من اجل سهوله تحميل الموقع والتنقل في لوحة التحكم
        </div>

        <div class="app-footer-line extended">
            <div class="row">
                <div class="col-md-4 col-sm-4">
                    <h3 class="title"> موقع </h3>
                    <p></p
                </div>
                <div class="col-md-4 col-sm-4">
                    <h3 class="title"><span class="icon-clipboard-text"></span> بعض الروابط المهمة </h3>
                    <ul class="list-unstyled">
                        <li><a href="/dashboard">الصفحة الرئيسية</a></li>
                    </ul>
                </div>
                <div class="col-md-4 col-sm-6">
                    <!--<h3 class="title"><span class="icon-thumbs-up"></span> روابط السوشيال ميديا</h3>-->

                    <!--<a href="#" class="label-icon label-icon-footer label-icon-bordered label-icon-rounded label-icon-lg">-->
                    <!--    <i class="fa fa-facebook"></i>-->
                    <!--</a>-->
                    <!--<a href="#" class="label-icon label-icon-footer label-icon-bordered label-icon-rounded label-icon-lg">-->
                    <!--    <i class="fa fa-twitter"></i>-->
                    <!--</a>-->
                    <!--<a href="#" class="label-icon label-icon-footer label-icon-bordered label-icon-rounded label-icon-lg">-->
                    <!--    <i class="fa fa-youtube"></i>-->
                    <!--</a>-->
                    <!--<a href="#" class="label-icon label-icon-footer label-icon-bordered label-icon-rounded label-icon-lg">-->
                    <!--    <i class="fa fa-google-plus"></i>-->
                    <!--</a>-->
                    <!--<a href="#" class="label-icon label-icon-footer label-icon-bordered label-icon-rounded label-icon-lg">-->
                    <!--    <i class="fa fa-feed"></i>-->
                    <!--</a>

                </div>
            </div>
        </div>
        <div class="app-footer-line darken">
            <div class="copyright wide text-center">&copy;<a href=""> .</a></div>
        </div>
    </div>
   END APP FOOTER -->

    <!-- START APP SIDEPANEL -->

    <!-- END APP SIDEPANEL -->

    <!-- APP OVERLAY -->
    <div class="app-overlay"></div>
    <!-- END APP OVERLAY -->
</div>
<!-- END APP WRAPPER -->

<!-- IMPORTANT SCRIPTS -->
<script type="text/javascript" src="{{asset('admin/js/vendor/jquery/jquery.min.js')}}"></script>
<script type="text/javascript" src="{{asset('admin/js/vendor/jquery/jquery-ui.min.js')}}"></script>
<script type="text/javascript" src="{{asset('admin/js/vendor/bootstrap/bootstrap.min.js')}}"></script>
<script type="text/javascript" src="{{asset('admin/js/vendor/moment/moment.min.js')}}"></script>
<script type="text/javascript" src="{{asset('admin/js/vendor/customscrollbar/jquery.mCustomScrollbar.min.js')}}"></script>
<!-- END IMPORTANT SCRIPTS -->


@yield('footer')

<!-- END THIS PAGE SCRIPTS -->
<!-- APP SCRIPTS -->
<script type="text/javascript" src="{{asset('admin/js/app.js')}}"></script>
<script type="text/javascript" src="{{asset('admin/js/app_plugins.js')}}"></script>
<script type="text/javascript" src="{{asset('admin/js/app_demo.js')}}"></script>
<!-- END APP SCRIPTS -->
<script type="text/javascript" src="{{asset('admin/js/app_demo_dashboard.js')}}"></script>


<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

<script>
    $.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        }
    });
</script>
@if(Session::has('message'))

@if(Session::get('status', 'info')=="success")
<script type="text/javascript">
    $(function() {
    "use strict";

    var SweetAlert = function() {};

    //examples
    SweetAlert.prototype.init = function() {

    //Success Message
    setTimeout(function(){
        swal({
            title: "عملية ناجحة",
             type: "success",
            text: "تمت العملية بنجاح",
            confirmButtonColor: "#8BC34A",
            timer: 2000,
            showConfirmButton: false
        });
     }, 3000);


    },
    //init
    $.SweetAlert = new SweetAlert, $.SweetAlert.Constructor = SweetAlert;

    $.SweetAlert.init();
});
</script>
@endif
@endif

  <script>
    $(document).ready(function() {
    if($('.datatable-extended').length) {
          $('.datatable-extended').DataTable({
              dom: 'Bfrtip',

              bDestroy: true,
              buttons: [
                  'copyHtml5',
                  'excelHtml5',
                  'csvHtml5',
                  'pdfHtml5'
              ]
          });
        }
    });
  </script>
  <script >
  $( document ).ready(function() {
  $( ".copyit" ).click(function( event ) {
    event.preventDefault();
    var id = $(this).attr('idk');
    var $temp = $("<input>");
    $("body").append($temp);
    $temp.val(id).select();
    document.execCommand("copy");
    $temp.remove();
     alert("تم النسخ" );
  });
  });



  </script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/dataTables.buttons.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.html5.min.js"></script>

</body>
</html>

resources/views/admin/map.blade.php
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC6v5-2uaq_wusHDktM9ILcqIrlPtnZgEk">
</script>
<script type="text/javascript">
    /*********************************/
    function GetfromAddress(lat,lng) {
        var lat = parseFloat(lat);var lng = parseFloat(lng);
        var latlng = new google.maps.LatLng(lat, lng);
        var geocoder = geocoder = new google.maps.Geocoder();
        geocoder.geocode({ 'latLng': latlng }, function (results, status) {
            if (status == google.maps.GeocoderStatus.OK) {
                if (results[1]) {
                    //alert("Location: " + results[1].formatted_address);
                    document.getElementById("addresss_to").value = results[1].formatted_address;
                }/*else if (results[0]) {
                //alert("Location: " + results[1].formatted_address);
    document.getElementById("addresss").value = results[0].formatted_address;
            }*/
            }
        });
    }

    function GetToAddress(lat,lng) {
        var lat = parseFloat(lat);var lng = parseFloat(lng);
        var latlng = new google.maps.LatLng(lat, lng);
        var geocoder = geocoder = new google.maps.Geocoder();
        geocoder.geocode({ 'latLng': latlng }, function (results, status) {
            if (status == google.maps.GeocoderStatus.OK) {
                if (results[1]) {
                    //alert("Location: " + results[1].formatted_address);
                    document.getElementById("addresss_from").value = results[1].formatted_address;
                }/*else if (results[0]) {
                //alert("Location: " + results[1].formatted_address);
    document.getElementById("addresss").value = results[0].formatted_address;
            }*/
            }
        });
    }

    function initialize() {
        var fromLat = {!! $trip->lat_from!!}
        var fromLon = {!! $trip->long_from!!}
            GetfromAddress(fromLat.toFixed(5),fromLon.toFixed(5));
        var toLat = {!! $trip->lat_to!!}
        var toLon = {!! $trip->long_to!!}
        GetToAddress(toLat.toFixed(5),toLon.toFixed(5));

    }

    window.onload = function () { initialize() };
</script>



<div class="form-group">
    <label for="computer">الشحنه من :</label>
    <input type="text" id="addresss_to" name="address" class="form-control" disabled="">

    <label for="computer">الشحنه الى :</label>
    <input type="text" id="addresss_from"  class="form-control" disabled="">

    <center>
        <!-- MAP HOLDER -->
        <!-- /MAP HOLDER -->
    </center>

</div>

resources/views/admin/navi.blade.php
<div class="topbar-menu">
    <div class="container-fluid">
        <div id="navigation">
            <!-- Navigation Menu-->
            <ul class="navigation-menu">

                <li class="has-submenu">
                    <a href="{{url('admin/index')}}">
                        <i class="mdi mdi-view-dashboard"></i>الرئيسية
                    </a>
                </li>

                <li class="has-submenu">
                    <a href="#">
                        <i class="mdi mdi-format-underline"></i>ادارة الطلبات <div class="arrow-down"></div>
                    </a>
                    <ul class="submenu megamenu">
                        <li>
                            <ul>
                              <li><a href="{{route('Order.index')}}">كل الطلبات</a></li>
                                {{-- <li><a href="{{route('Order.index')."?status=1"}}">الطلبات الحالية</a></li>--}}
                            </ul>
                        </li>
                    </ul>
                </li>



                <li class="has-submenu">
                    <a href="#">
                        <i class="mdi mdi-package-variant-closed"></i>ادارة السائقين <div class="arrow-down"></div></a>
                        <ul class="submenu">
                            <li><a href="{{route('Driver.index')}}">كل السائقين</a></li>

                        </ul>
                </li>
                <li class="has-submenu">
                    <a href="#">
                        <i class="mdi mdi-package-variant-closed"></i>ادارة المستخدمين <div class="arrow-down"></div></a>
                        <ul class="submenu">
                            <li><a href="{{route('User.index')}}">المستخدمين</a></li>
                        </ul>
                </li>

                <li class="has-submenu">
                    <a href="#">
                        <i class="mdi mdi-package-variant-closed"></i>ادارة اصحاب الاعمال <div class="arrow-down"></div></a>
                        <ul class="submenu">
                            <li><a href="{{route('Business.index')}}">كل اصحاب الأعمال</a></li>
                        </ul>
                </li>
                <li class="has-submenu">
                    <a href="#">
                        <i class="mdi mdi-package-variant-closed"></i>ادارة الزبائن  <div class="arrow-down"></div></a>
                        <ul class="submenu">
                            <li><a href="{{route('Client.index')}}">كل الزبائن </a></li>
                        </ul>
                </li>

                <li class="has-submenu">
                    <a href="#">
                        <i class="mdi mdi-package-variant-closed"></i>ادارة المحصلين  <div class="arrow-down"></div></a>
                        <ul class="submenu">
                            <li><a href="{{route('Collector.index')}}">كل المحصلين </a></li>
                        </ul>
                </li>

                {{-- <li class="has-submenu">
                    <a href="#"> <i class="mdi mdi-flip-horizontal"></i>الثوابت <div class="arrow-down"></div></a>
                    <ul class="submenu">
                      @php

                        $ddk[]=['name'=>"Setting",'label'=>"ثوابت التطبيق"];
                        $ddk[]=['name'=>"Advantage",'label'=>"ميزات السيارات"];
                      $ddk  []=['name'=>"Carmodel",'label'=>"موديلات السيارات"];
                      @endphp

                      @foreach ($ddk  as $inc)
                        <li >
                            <a href="{{route($inc['name'].'.index')}}">{{$inc['label']}} </a>
                        </li>
                      @endforeach

                    </ul>
                </li> --}}




            </ul>
            <!-- End navigation menu -->

            <div class="clearfix"></div>
        </div>
        <!-- end #navigation -->
    </div>
    <!-- end container -->
</div>
<!-- end navbar-custom -->